### ISSUE TITLE
Problems with Xaero's Map and killing mobs

### ISSUE THREAD

**Issue by RockZe** [Globox1997/PartyAddon#1]
### Minecraft Version

1.19.x

### Mod Loader Version

0.14.18

### Mod Version

partyaddon-1.0.0.jar

### Describe the Issue

I installed the Party addon, thanks for it, the addon is really great! However, I noticed that the addon is not good friends with Xaero's Minimap and Xaero's World Map, when opening the map it throws it from the server (unfortunately, I can't throw off the error now). And also, when killing some mobs, it can also be thrown off the server, with such an error in the console:
Caused by: java.lang.NullPointerException: Cannot invoke "net.partyaddon.access.GroupLeaderAccess.addLeaderLevelZExperience(int)" because the return value of "net.minecraft.class_1937.method_18470(java.util.UUID)" is null

And this is a screenshot of the error when opening map:
![2023-05-22_00-30-17](https://github.com/Globox1997/PartyAddon/assets/123874691/1a7b4ff5-1b54-49ab-9292-c48a1a55354d)

### latest.log

[crash-2023-04-21_19.21.52-client.txt](https://github.com/Globox1997/PartyAddon/files/11525618/crash-2023-04-21_19.21.52-client.txt)

**Comment by Globox1997** [comment]
Fixed null pointer with [https://github.com/Globox1997/PartyAddon/commit/87efbe7d0b8d5a88c10f466891e454c9e473067a](https://github.com/Globox1997/PartyAddon/commit/87efbe7d0b8d5a88c10f466891e454c9e473067a)
Fixed world map crash with [https://github.com/Globox1997/PartyAddon/commit/31435d2fabbf4b2bc0d49ef204e64edda94b7aa2](https://github.com/Globox1997/PartyAddon/commit/31435d2fabbf4b2bc0d49ef204e64edda94b7aa2)
Your crash log is not the latest log and the crash inside it has nothing to do with party addon ;)
Thanks for reporting
