### ISSUE TITLE
Another problem with Xaero's World Map

### ISSUE THREAD

**Issue by RockZe** [Globox1997/PartyAddon#2]
### Minecraft Version

1.19.x

### Mod Loader Version

0.14.18

### Mod Version

partyaddon-1.0.1.jar

### Describe the Issue

I found another problem with **`Xaero's World Map`**. When installed **`partyaddon-1.0.1.jar`** opening a map from **`Xaero's World Map`** mod creates an unpleasant effect when the map opens at zero coordinates, instead of opening at the player's current location. 
The settings of **`Xaero's World Map`** do not give any changes, only the removal of the mod **`partyaddon-1.0.1.jar`** fixes the problem. I hope you can solve this unpleasant bug! Thank you for your hard work!

### latest.log

Unfortunately, there is no feedback in my logs about the work of these mods (or I do not know where to look)

### Do you use any other mods except the required ones?

Xaero's World Map, Xaero's MiniMap

**Comment by Globox1997** [comment]
Thanks for reporting, fixed with [https://github.com/Globox1997/PartyAddon/commit/3e4554c66be7c429f47b39f7334b8bd12257f90d](https://github.com/Globox1997/PartyAddon/commit/3e4554c66be7c429f47b39f7334b8bd12257f90d)
