### ISSUE TITLE
Crash with Xaero Plus

### ISSUE THREAD

**Issue by haiyaoxliu** [Globox1997/PartyAddon#4]
### Minecraft Version

1.20.x

### Mod Loader Version

0.14.22

### Mod Version

1.0.3

### Describe the Issue

Game crashes on startup with xaero's world map, xaero's minimap, and xaero plus installed.
Remove XaeroPlus and it starts fine.

### latest.log

[latest.log](https://github.com/Globox1997/PartyAddon/files/12565256/latest.log)

### Do you use any other mods except the required ones?

Xaero's World Map, Xaero's Minimap, XaeroPlus

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/PartyAddon/commit/01aa9ddbdbb36a68f1f376b252c2a3d41ea4b338](https://github.com/Globox1997/PartyAddon/commit/01aa9ddbdbb36a68f1f376b252c2a3d41ea4b338)
